name: Deploy stage

on: 
  pull_request:
    branches:
      - stage
  push:
    branches:
      - stage      

permissions:
  contents: read

jobs:
  deploy:
    name: CD Pipeline stage
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      # --- PASSO ADICIONADO: Instala o Terraform no Runner ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials stage  
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
          aws-region: us-east-1

      - name: Terraform Init    
        run: terraform init -reconfigure -backend-config=../config/backend/stage.tfbackend

      - name: Terraform Validate    
        run: terraform validate

      - name: Terraform Format    
        run: terraform fmt -recursive

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'    
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/stage'    
        run: terraform apply -input=false -auto-approve

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Build React App
        working-directory: ./
        run: |
          npm install
          npm run build

      - name: Sync to S3 Stage
        working-directory: ./
        if: github.event_name == 'push' && github.ref == 'refs/heads/stage'
        run: aws s3 sync ./build s3://react-app-app-wf-default --delete        
